### PR TITLE
Seekbar

### PR DESCRIPTION
**Pull request by pureooze**
Simple change to increase the size of the slider button, just makes it a bit easier to use the volume slider.

### CODE REVIEW

**Comment by ForeEyes** [comment]
Can you also make the player slider thinner...

**Comment by pureooze** [comment]
Did you mean something like this:
image


Or this?
image

**Comment by ForeEyes** [comment]
The first one look awesome. when the user drags, does it pull to the dots?

**Comment by pureooze** [comment]
Yep

**Comment by ForeEyes** [comment]
then use the first one!

**Pull request merged**
