### PR TITLE
Add Media playback

### LINKED ISSUE #2: Add media playback for podcast audio files
We should add audio playback functionality for the podcasts. The playback should start when a user clicks the play button, and pause/stop when  a user clicks the respective button. The correct file to play should be determined based on the users CURRENT selection in the episodeList.

### PR DESCRIPTION
**Pull request by pureooze**
This PR resolves #2 and enables the user to play, pause and stop media file playback. I tried my best to merge and keep the widgets. I think I forgot to add the skip forward and backward buttons but we can add those in a later PR (or if you want I can revise this to include that).

Let me know your thoughts on this, thanks.

### CODE REVIEW

**Comment by ForeEyes** [comment]
Dude, this looks good, but i have some changes:

- i am going to extend the episodeFile function to return the play time(length of episode in seconds)
- use this to set the max value of the slider
-Second: take a look at this layout:
image
This way the user can play the selected podcast, then browse through the catalog, and if they want to play a different episode they can click the play current button again, which will replace the currently playing episode.... Also the pause will switch to resume when the audio is pasued

**Comment by pureooze** [comment]
Okay cool, so are you going to accept the merge request? 

1. If you want I can change it to do that as I am working on the skip forward and backward functionality atm (see https://github.com/pureooze/PodcastFeed/commit/c0d8351dd3e17d7921ab6ed99dc78b8bbc0f16a5). Is there a reason why we need to return the duration? Can't it always be accessed via player->duration()?

2. I think the "Play Selection" button could be put in the description pane, that might make it look a bit better? It could be doable and it would then eliminate the scenario where a user clicks the button without having actually selected a podcast (although we can also use the hidden() property for this when tracking the clicks in the episodePane if you don't want to hide the button inside the descriptions pane)

Oh and the volume slider seems a bit big lol. Other than that, I think the interface looks good.

**Comment by ForeEyes** [comment]
player->duration only works for local files, when they are being streamed the duration will return 0.

**Comment by pureooze** [comment]
Ah I see so how would we find out how long the file is when it is streamed?

**Comment by ForeEyes** [comment]
the xml file includes the episode duration in seconds...so i will make the function accept a reference for duration and parse the time into that variable...

**Comment by pureooze** [comment]
Okay sounds good, I'll make an issue for that and assign to you.

**Comment by ForeEyes** [comment]
nevermind, i found a way...use this connect before playing: 
`connect(player, SIGNAL(durationChanged(qint64)), this, SLOT(setSliderRange(qint64)));`
` connect(player, SIGNAL(positionChanged(qint64)), this, SLOT(positionChanged(qint64)));`
then the setSliderRange function:
```
void MainWindow::setSliderRange(qint64 duration){
        qDebug() << duration;
        ui->playerSlider->setRange(0, duration);
}
```
the the positionChanged function : 
```
void MainWindow::positionChanged(qint64 timeElapsed){
    ui->playerSlider->setValue(timeElapsed);
}
```

This will interfere with user moving the slider, so need to figure that out....

**Pull request merged**
